#alias e 'code'
alias g 'git'
alias iauploadcheckderive 'ia upload --checksum --verify --retries 50 --no-backup'
alias iauploadfastderive 'ia upload --verify --retries 50 --no-backup'
alias iauploadcheck 'ia upload --checksum --verify --retries 50 --no-backup --no-derive'
alias iauploadfast 'ia upload --verify --retries 50 --no-backup --no-derive'
alias vts 'vitetris -listen 27015'
